# Epilogue

These workshops have only really scratched the surface as to what can be achieved using `tidyverse` and R. We haven't touched on the apply functions included in the [`purrr`](https://github.com/rstudio/cheatsheets/raw/master/purrr.pdf) package; we haven't looked at the utility of **list-columns**; or began to explore the myriad other `ggplot2` geoms, such as `geom_violin()`, `geom_bar()` or `geom_hex()`. We haven't looked at packages such as [`gganimate`](https://github.com/thomasp85/gganimate), or [`plotly`](https://plot.ly/r/) for turning your R plots into interactive HTML graphics, or the wonderful [`shiny`](https://shiny.rstudio.com/gallery/) package for creating fully interactive websites, or the use of [`knitr`](https://yihui.name/knitr/) and [`rmarkdown`](https://rmarkdown.rstudio.com/) to produce fully reproducible documents. In fact this workshop was written completely in R using the [`bookdown`](https://bookdown.org/yihui/bookdown/) package, by the inimitable [Yihui Xie](https://en.wikipedia.org/wiki/Yihui_Xie) (who also wrote `knitr`).

I hope that this workshop has helped to spark your interest in some of the more powerful features of R. Please browse the myriad `ggplot2` or `shiny` galleries for inspiration, and don't hesitate to ask if you have any further questions. 