``{r, echo = FALSE, results = "asis"}
x <- paste("
---
title: \"Sexual activity in fruitflies\"
author: TJ McKinley
output: html_document
---

`{r, include = FALSE, purl = FALSE}
knitr::opts_chunk$set(echo = TRUE)
`{e}

# Introduction

A cost of increased reproduction in terms of reduced longevity has been shown for female fruitflies, but not for males. This experiment used a factorial design to assess whether increased sexual activity affected the lifespan of male fruitflies.

The flies used were an outbred stock. Sexual activity was manipulated by supplying individual males with one or eight receptive virgin females per day. The longevity of these males was compared with that of two control types. The first control consisted of two sets of individual males kept with one or eight newly inseminated females. Newly inseminated females will not usually remate for at least two days, and thus served as a control for any effect of competition with the male for food or space. The second control was a set of individual males kept with no females. There were 25 males in each of the five groups, which were treated identically in number of anaesthetizations (using CO2) and provision of fresh food medium.

The data should have the following columns:

* **partners**: number of companions (0, 1 or 8);
* **partner type**: type of companion (`Control`, `Inseminated`, `Virgin`);
* **longevity**: lifespan, in days;
* **thorax**: length of thorax, in mm.

Source: [Partridge and Farquhar (1981)](http://www.annualreviews.org/doi/pdf/10.1146/annurev.pu.04.050183.001103)

# Analysis

First we load and reformat the data set:

`{r, message = FALSE}
## load libraries
library(tidyverse)

## load data
ff <- read_csv(\"ff.csv\")

## convert columns to correct format
## and simplify column names
ff <- mutate(ff, partners = as.character(partners)) %>%
    rename(partner_type = `partner type`)
`{e}

Now we plot `longevity` against `thorax`, stratified by the different experimental conditions. We use a simple linear regression model to capture the trends within each experimental group.

`{r}
## produce summary plot
ggplot(ff, aes(y = longevity, x = thorax, 
               linetype = partner_type, 
               shape = partner_type)) +
    geom_point() +
    stat_smooth(method = \"lm\", se = FALSE) +
    facet_wrap(~partners) +
    labs(linetype = \"Partner Type\", 
         shape = \"Partner Type\") +
    ylab(\"Longevity (days)\") +
    xlab(\"Thorax length (mm)\") +
    theme_bw()
`{e}

We can see that there is a strong linear relationship between `thorax` and `longevity`, such that larger flies tend to live longer. On top of this the data suggest that males housed with virgin partners show decreased longevity compared to the control group, where as males housed with inseminated partners exhibited similar longevity trends to the control group. We also note that males housed with multiple virgin partners exhibit a larger decrease in longevity on average than those housed with a single virgin partner. This suggests that increased reproductive effort may result in decreased longevity in fruit flies. A more formal statistical analysis should be undertaken to quantify these effects more rigorously.")

x <- gsub("`\\{r", "``\\{r", x)
x <- gsub("`\\{e\\}", "``", x)
if(opts_knit$get("rmarkdown.pandoc.to") == "html") {
    x <- paste("<pre><code>\n", x, "</code></pre>")
} else {
    x <- paste("\\begin{lstlisting}\n", x, "\\end{lstlisting}")
}
cat(x)
``
